### ISSUE TITLE
How do you get push and install to work from Flutter?

### ISSUE THREAD

**Issue by lanzorg** [nightmare-space/adb_tool#10]
Hi mengyanshou,

I successfully used your adb binary on my Flutter application like so.

```dart
// Make the binary executable.
final folder = (await getTemporaryDirectory()).path;
final binary = p.join(folder, "adb");
await Process.run('chmod', ['+x', binary]);

// Shell command is working.
var serial = "192.168.1.20";
var extras = ['shell', 'echo helloworld'];
var result = await Process.run(binary, ['-s', serial, ...extras]);
var output = result.stdout.trim(); // helloworld
```

Unfortunately I can't make the push and install commands working.

```dart
// Push command is failing.
var record = p.join(folder, 'record.log'); // File exists.
extras = ['push', record, '/sdcard/record.log'];
result = await Process.run(binary, ['-s', serial, ...extras]);
var errors = result.stderr.trim(); // adb: error: failed to stat remote object '/data/user/0/com.example.myapp/cache/record.log': No such file or directory
```

Could you tell me what is missing to make these commands work?

Hope I am not annoying you and thanks in advance.

**Comment by sharpordie** [comment]
I'm really sorry, everything works after a complete reinstallation of flutter (probably a problem of cache that was not deleted). I was distracted by your adbutil package and thought I had to do a lot of complicated stuff to run push and install commands. The previous code works perfectly. You can just delete this issue if you want.

**Comment by lanzorg** [comment]
I'm really sorry, everything works after a complete reinstallation of flutter (probably a problem of cache that was not deleted). I was distracted by your adbutils package and thought I had to do a lot of complicated stuff to run push and install commands. The previous code works perfectly. You can just delete this issue if you want.

**Comment by mengyanshou** [comment]
okk~
