### ISSUE TITLE
是否可能本机通过adb tcp模式连接本地adb server，并打开一个adb shell

### ISSUE THREAD

**Issue by lzb6666** [nightmare-space/adb_tool#11]
如标题，在当前的终端模拟器里面试了下，没有成功。本地指Android设备

**Comment by mengyanshou** [comment]
首页连接127.0.0.1就行了，前提，手机打开无线调试，如何打开能查到

**Comment by lzb6666** [comment]
嗯，试了下成功了。区别在于，打开无线调试配对的时候，需要使用分屏模式，一旦无线调试配对的窗口进入后台，就无法成功配对。这也是为什么上面没有成功。

**Comment by lzb6666** [comment]
另外想请教下，交叉编译好的adb是直接放进assert目录打包的么

**Comment by mengyanshou** [comment]
对的，带上所依赖的动态库，也可以静态编译，但是我不会，不过在https://github.com/Magisk-Modules-Repo/adb-ndk有静态编译的adb，不过版本较低

**Comment by lzb6666** [comment]
发现我复制到私有目录之后运营会报权限错误
