### ISSUE TITLE
请问本仓库使用的Flutter SDK版本是多少

### ISSUE THREAD

**Issue by Joehaivo** [nightmare-space/adb_tool#13]
我用Flutter 3.7.3 无法编译成功
Flutter (Channel stable, 3.7.3, on Microsoft Windows [版本 10.0.19044.1415], locale zh-CN)

**Comment by Joehaivo** [comment]
在pubspec.lock中找到了
  dart: ">=2.17.0 <3.0.0"
  flutter: ">=3.1.0-0"

**Comment by mengyanshou** [comment]
目前dev分支是flutter 3.7.1
