### ISSUE TITLE
你好想问一下AdbConnection这个类中的open方法参数

### ISSUE THREAD

**Issue by Puffer987** [nightmare-space/adb_tool#2]
adbConnection.open(参数) 里面的参数填写的是什么作用的，有相关的文档吗，要填写什么才是执行adb指令，而不是adb shell指令。

希望能得到您的解答。o(╥﹏╥)o
-----来自酷友的疑惑

**Comment by mengyanshou** [comment]
这个connection相当于adb上一层的协议，你可以看这行代码，https://github.com/nightmare-space/adb_tool/blob/0cd2accc1d40991a929a4d118545c42c216b0c3e/android/app/src/main/java/com/nightmare/adbtools/MainActivity.java#L80
参考文章 https://juejin.cn/post/7034799230086545445?share_token=de7eb75f-7b68-4aeb-868c-3ba34872cbf3
协议参考 https://link.juejin.cn/?target=http%3A%2F%2Fandroidxref.com%2F8.1.0_r33%2Fxref%2Fsystem%2Fcore%2Fadb%2FSERVICES.TXT%3Fmode%3Dlight
总之还挺复杂的🤪

**Comment by Puffer987** [comment]
谢谢大佬回复，我看看你写的文章先
