### ISSUE TITLE
更新道路还很长啊

### ISSUE THREAD

**Issue by wcwq98** [nightmare-space/adb_tool#28]
1.优化软件性能，主要问题∶软件不流畅特别卡顿有时候还加载不出来应用列表
2.无法投屏(控制)
3.无法显示设备的应用图标
4.无法显示安卓版本
5.无法提取安装包，无法对已安装应用进行操作，如∶卸载，提取，强停，冻结，
6.无法显示进程
7.无法修改dpi
测试平台:连接端∶手机mate30pro 鸿蒙4.2
被连接端: oppo watch2 安卓版本8.1

**Comment by Laurie-Lin** [comment]
因为世人总想着不劳而获，任何的开源，他们也都只会指出问题

**Comment by wcwq98** [comment]
嗯也是，那我关issues了

**Comment by Laurie-Lin** [comment]
你反馈的这些我都记下来了，等精力空闲会来修复
