### ISSUE TITLE
大佬，考虑写一个c版本的吗

### ISSUE THREAD

**Issue by sbmatch** [nightmare-space/adb_tool#29]
我最近有一个想法，使用单片机stm32f4系列控制Android设备，比如adb push一份dex 然后执行它 这样就有shell权限执行miui-framework.jar 中的Lmiui/security/AppRunningControlManager;->setDisallowRunningList(Ljava/util/List;Landroid/content/Intent;)V  控制应用是否可以被启动 也可以Landroid/miui/AppOpsUtils;->setApplicationAutoStart(Landroid/content/Context;Ljava/lang/String;Z)V  设置应用自启动 刚好大佬你的这个项目的有我需要的方法 push 和命令执行😌

**Comment by Laurie-Lin** [comment]
我不可能再编写一个C语言版本的ADB KIT的，你在单片机上，直接检查编译一个adb上去就行，没必要为了少数的需求，而投入极大量的精力去重构一个软件
